version: "3.8"

services:
  biolink_bot:
    build: .
    container_name: biolink_protector
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot_data.json:/app/bot_data.json
